# APS 4 - PROJETO DE SOFTWARE PARA ANÁLISE DE TRELIÇAS PLANAS

In [1]:
from funcoesTermosol import geraSaida, importa, plota
import numpy as np
from math import sqrt 


In [18]:
# numero de nos [nn]
# matriz dos nos [N]
# numero de membros [nm]
# matriz de incidencia [Inc]
# numero de cargas [nc]
# vetor carregamento [F]
# numero de restricoes [nr]
# vetor de restricoes [R]


matriz_um = np.array([[1, -1], [-1, 1]])


class Node:
    def __init__(self, x, y):
        self.x = x
        self.y = y


class Elemento:
    def __init__(self, no1, no2, E, A):
        self.E = E
        self.A = A
        self.l = sqrt((no1.x - no2.x)**2 + (no1.y - no2.y)**2)
        self.cos = (no2.x - no1.x)/self.l
        self.sin = (no2.y - no1.y)/self.l
        self.T = np.array([[self.cos, self.sin, 0, 0],
                          [0, 0, self.cos, self.sin]])
        self.T_transposta = np.transpose(self.T)

        self.ke = np.dot(np.dot(self.T_transposta *
                         (self.E*self.A/self.l), matriz_um), self.T)


[nn, N, nm, Inc, nc, F, nr, R] = importa('entrada.xls')
A = 2e-4
E = 210e9
Py = -100
Px = 150
sigma_tracao = 1570e6
sigma_compressao = sigma_tracao

# criar um objeto Node para cada no
node1 = Node(N[0, 0], N[1, 0])
node2 = Node(N[0, 1], N[1, 1])
node3 = Node(N[0, 2], N[1, 2])

Elemento12 = Elemento(node1, node2, Inc[0, 2], Inc[0, 3])
Elemento23 = Elemento(node2, node3, Inc[1, 2], Inc[1, 3])
Elemento31 = Elemento(node3, node1, Inc[2, 2], Inc[2, 3])



rigidez1 = Elemento12.ke
rigidez2 = Elemento23.ke
rigidez3 = Elemento31.ke

# Create a global stiffness matrix superpositioning the local stiffness matrices
K = np.zeros((2*nn, 2*nn))
K[0:4, 0:4] += rigidez1
# K[3:6, 3:6] += rigidez2
# K[5:6, 5:6] += rigidez3
# K[1:2, 1:2] += rigidez3

print(K)









# matriz de rigidez de um elemento
# [Ke] = E*A/l * [T]
# [T] = [[cos  0 ]  * [[1  -1]   *   [[cos  sen  0    0 ]
#        [sen  0 ]     [-1  1]]       [ 0    0  cos  sen]]
#        [ 0  cos]
#        [ 0  sen]]

# cos = (x2 - x1)/L
# sen = (y2 - y1)/L
# L = sqrt( (x2 - x1)**2  +  (y2 - y1)**2 )

# dx =
# dy =

# L = sqrt()


a = np.array([[1, 2], [3, 4]])


[[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  1.05e+08  0.00e+00 -1.05e+08  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00 -1.05e+08  0.00e+00  1.05e+08  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]]
